// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sapient-ibkr/AITradingInbox.tsx": () => import("../components/mockups/sapient-ibkr/AITradingInbox.tsx"),
  "./components/mockups/sapient-ibkr/AITradingSettings.tsx": () => import("../components/mockups/sapient-ibkr/AITradingSettings.tsx"),
  "./components/mockups/sapient-ibkr/BrokerageSettings.tsx": () => import("../components/mockups/sapient-ibkr/BrokerageSettings.tsx"),
  "./components/mockups/sapient-ibkr/PortfolioExecute.tsx": () => import("../components/mockups/sapient-ibkr/PortfolioExecute.tsx")
};
